version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true     
      - FAST_REFRESH=true
    volumes:
      - .:/app                      
      - /app/node_modules
    networks:
      - inner-net      

networks:
  inner-net:
    external: true